name: NowYouAreSteelRat
version: 0.1.0.0
github: "DeniLark/NowYouAreSteelRat"
license: BSD3
author: "DeniLark"
maintainer: "denlarsites@gmail.com"
copyright: "2023 DeniLark"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/DeniLark/NowYouAreSteelRat#readme>

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - bytestring
  - text
  - telegram-bot-simple
  - containers
  - mtl
  - directory
  - random
  - split

default-extensions:
  - DeriveGeneric

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  # - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  NowYouAreSteelRat-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - NowYouAreSteelRat

tests:
  NowYouAreSteelRat-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - NowYouAreSteelRat
